const ImagesAll = {
  acc: require("../account-create.svg").default,
  acSet: require("../accountsettings.svg").default,
  add: require("../add.svg").default,
  arrF: require("../arrow_forward.svg").default,
  b3: require("../b3.jpg").default,
  b4: require("../b4.jpg").default,
  blkB: require("../back-iceblue.svg").default,
  blkW: require("../back-white.svg").default,
  bg1: require("../bg01.jpg").default,
  bookB: require("../book-balck.svg").default,
  booK: require("../book-hover.svg").default,
  book: require("../book.svg").default,
  cal: require("../calendar.svg").default,
  cal: require("../dashboard-hover.svg").default,
  cal: require("../dashboard.svg").default,
  cal: require("../delete-iceblue.svg").default,
  cal: require("../delete-white.svg").default,
  cal: require("../doctors-hover.svg").default,
  cal: require("../doctors.svg").default,
  cal: require("../edit-iceblue.svg").default,
  cal: require("../edit-white.svg").default,
  cal: require("../filter-iceblue.svg").default,
  cal: require("../filter-white.svg").default,
  cal: require("../home-iceblue.svg").default,
  cal: require("../home.svg").default,
  cal: require("../info.svg").default,
  cal: require("../notfound.svg").default,
  cal: require("../patients-hover.svg").default,
  cal: require("../patients.svg").default,
  cal: require("../schedule-hover.svg").default,
  cal: require("../search.svg").default,
  cal: require("../session-iceblue.svg").default,
  cal: require("../session.svg").default,
  cal: require("../settings-iceblue.svg").default,
  cal: require("../settings.svg").default,
  cal: require("../user").default,
  cal: require("../view-gray.svg").default,
  cal: require("../view-iceblue.svg").default,
  cal: require("../view-white.svg").default,
//   cal: require("../").default,
//   cal: require("../view-gray.svg").default,
//   cal: require("../view-iceblue.svg").default,
};
export default ImagesAll;
